title:              Criminality in SF
email:              s230221@dtu.dk
description:        A blog that describes the criminality situation in SF
author:             Norma, Eliot and Alba
baseurl:            "/Assignment2_SFcriminality"
url:                "https://albacastrillo/Assignment2_SFcriminality"

# Social Profiles
twitter_username:   SBootstrap
github_username:    StartBootstrap
facebook_username:  StartBootstrap
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
