title:              Public Safety in San Francisco
email:              s230221@dtu.dk
description:        Demystifying criminality and bringing data to life
author:             Eliot, Alba and Norma
baseurl:            "/Assignment2_SFcriminality"
url:                "https://albacastrillo/Assignment2_SFcriminality"

# Social Profiles
twitter_username:   
github_username:     albacastrillo
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
